name: Despliegue automático

on:
  push:
    branches:
      - main  # O la rama en la que quieras que se ejecute

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configurar acceso SSH al servidor (si es necesario)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa presupon.com >> ~/.ssh/known_hosts

      - name: Desplegar el código al servidor
        run: |
          ssh jupiter@presupon.com '/home/jupiter/code/deploy.sh'
